Repository chandansgowda/engineering-in-kannada, pull requests merged in 2025-04, with the labels that each got.

#2 changed the tittle in index.html and added _redirects file
  index.html
  public/_redirects
Labels: bug

#19 Added X Twitter icon on footer in home page
  package-lock.json
  package.json
  src/components/Footer.tsx
Labels: good first issue

#18 feat: leaderboard for contributors
  .env.example
  .gitignore
  README.md
  src/App.tsx
  src/components/Header.tsx
  src/pages/LeaderboardPage.tsx
  src/services/github.ts
  src/types/index.ts
Labels: enhancement

#16 update: added C programming in kannada course
  src/data/courses.json
  src/data/videos/c-fundamentals.json
Labels: good first issue

#22 feat: show toast when a link doesn't exist
  package-lock.json
  package.json
  src/components/VideoCard.tsx
  src/index.css
  src/pages/CoursePage.tsx
  src/utils/toastWithCustomMessages.ts
  src/utils/useBreakPoint.ts
Labels: enhancement

#21 docs: Add Table of Contents to README
  README.md
Labels: documentation, good first issue

#29 Fixed link to github repo
  src/components/Header.tsx
Labels: bug, good first issue

#31 feat: Add NotesViewer component for displaying GitHub markdown content
  package-lock.json
  package.json
  src/components/NotesViewer.tsx
  src/components/VideoCard.tsx
  tailwind.config.js
Labels: enhancement

#32 feat: integrate google analytics
  .env.example
  index.html
  package-lock.json
  src/App.tsx
  src/utils/analytics.ts
Labels: enhancement

#34 Implemented blogs functionality
  README.md
  src/App.tsx
  src/blogs/blog-1/content.md
  src/blogs/blog-1/metadata.json
  src/components/Header.tsx
  src/pages/BlogPost.tsx
  src/pages/Blogs.tsx
  src/types/index.ts
  src/utils/blogUtils.ts
  src/utils/textUtils.ts
Labels: enhancement
